spring.application.name=SalesData


server.port=9090
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.url=jdbc:sqlserver://localhost\\SQLEXPRESS;databaseName=AdventureWorksDW;encrypt=true;trustServerCertificate=true
## spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=eShop;encrypt=false


# USE eShop;
# CREATE USER MyUser FOR LOGIN MyUser;
# ALTER ROLE db_owner ADD MEMBER MyUser;




spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
